server:
  port: 8081

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  thymeleaf:
    cache: false

logging:
  level:
    org.springframework.amqp: DEBUG
